### PR TITLE
feat(amqAutocomplete.user.js): allow for shift-tab to go backwards

### PR DESCRIPTION
**Pull request by Rickkwa**
Update autocomplete when `allowTab: true` to additionally allow the user to do shift+tab to go to the previous result.

### CODE REVIEW

**Review by Zolhungaj — APPROVED** [review]
Not a super fan of bracket-less ifs personally, but I guess the readability here is fine

**Comment by Rickkwa** [comment]
I am also not a fan but I kept the existing style conventions of the file.

**Comment by Zolhungaj** [comment]
@Rickkwa could you bump the version number too while you're at it.

**Comment by Zolhungaj** [comment]
Wait never mind I can probably do that manually.

**Comment by Rickkwa** [comment]
> Wait never mind I can probably do that manually.

thanks

**Pull request merged**
